package com.orhava.trivia2;

import static com.orhava.trivia2.MainMenu.flag;
import static com.orhava.trivia2.MainMenu.i;

import android.content.Intent;
import android.media.MediaPlayer;
import android.os.Bundle;
import android.os.Handler;
import android.widget.ImageButton;
import android.widget.TextView;
import android.widget.Toast;

import androidx.appcompat.app.AppCompatActivity;

import com.google.android.gms.ads.AdRequest;
import com.google.android.gms.ads.AdSize;
import com.google.android.gms.ads.AdView;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Objects;

public class Fun_Facts extends AppCompatActivity {
   private  ImageButton navToMain,mute_unmute,Btn_Next_Fact;
    private TextView Txt_Fact;
    private ArrayList<String> MyFacts;
    int currentIndex = 0;


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_fun_facts);
        Objects.requireNonNull(getSupportActionBar()).hide();
        navToMain= findViewById(R.id.navToMain);
        mute_unmute= findViewById(R.id.mute_unmute);
        Txt_Fact= findViewById(R.id.Txt_Fact);
        Btn_Next_Fact= findViewById(R.id.Btn_Next_Fact);
        if (i[0] % 2==0) {
            mute_unmute.setImageResource(R.mipmap.mutenewproblem11);

        } else {
            mute_unmute.setImageResource(R.mipmap.mutenewproblem22);
        }

        NextFact();

        // Find the AdView element in your layout
        AdView adView = findViewById(R.id.adView);

        // Create an ad request
        AdRequest adRequest = new AdRequest.Builder().build();

        // Load the ad into the AdView
        adView.loadAd(adRequest);


        ButtonsNav();
        Mute_UnMute();

    }

    private void NextFact() {


        MyFacts = new ArrayList<>(Arrays.asList("1. The Vatican City is the smallest country in the world, with an area of just 0.17 square miles.","2. The Maldives is the flattest country in the world, with no land rising more than six feet above sea level.", "3. The world's longest recorded name for a place is Taumatawhakatangihangakoauauotamateaturipukakapikimaungahoronukupokaiwhenuakitanatahu, which is a hill in New Zealand.", "4. The United States has more tornadoes than any other country in the world.","5. Bhutan is the only country in the world that uses Gross National Happiness (GNH) as an official measure of success.","6. The largest castle in the world is Malbork Castle in Poland, which covers an area of over 52 acres.",
                "7. The highest waterfall in the world is Angel Falls in Venezuela, which drops over 3,200 feet.", "8. The only country in the world with no rivers is Saudi Arabia.","9. Russia is the largest country in the world by land area, covering over 17 million square kilometers.","10. The world's largest diamond was found in South Africa in 1905 and weighed over 3,000 carats.", "11. Canada has the longest coastline in the world, stretching over 202,000 kilometers.",
                "12. The world's largest desert is the Sahara, covering over 3.6 million square miles across North Africa.","13. The world's oldest university still in operation is the University of Bologna in Italy, which was founded in 1088.",
                "14. The highest point in Africa is Mount Kilimanjaro, which stands at 19,341 feet.", "15. The Great Barrier Reef in Australia is the world's largest coral reef system, covering over 2,300 kilometers.", "16. The world's largest man-made structure is the Great Wall of China, which stretches over 13,000 miles.","17. The only country in the world that is also a continent is Australia.","18. The world's largest island is Greenland, which covers over 840,000 square miles.", "19. The country with the most languages spoken is Papua New Guinea, with over 820 different languages.", "20. The largest city in the world by population is Tokyo, Japan, with over 37 million people.","21. The smallest mammal in the world is the bumblebee bat, which is found in Thailand and weighs less than a penny.","22. The driest place on earth is the Atacama Desert in Chile, where some areas have not seen rain in over 400 years.", "23. The world's largest oil reserves are located in Venezuela, with over 300 billion barrels.",
                "24. The largest temple in the world is Angkor Wat in Cambodia, covering over 162 hectares.","25. The fastest land animal in the world is the cheetah, which can run up to 70 miles per hour.","26. The country with the highest life expectancy is Japan, where people can expect to live an average of 84 years.", "27. The world's largest cave system is the Mammoth Cave National Park in Kentucky, USA.", "28. The largest freshwater lake in the world by volume is Lake Baikal in Russia, which contains over 20% of the world's freshwater.","29. The tallest building in the world is the Burj Khalifa in Dubai, standing at over 828 meters tall.","30. The world's largest producer of cocoa is Cote d'Ivoire (Ivory Coast), which produces over 40% of the world's cocoa beans."));


        MyFacts.addAll(Arrays.asList(
                "31. Norway is home to the Midnight Sun, where the sun doesn't set for about 76 days during summer.",
                "32. The national animal of Scotland is the unicorn.",
                "33. Iceland is a country with no mosquitoes.",
                "34. Singapore is the only country in the world without farmland.",
                "35. The world's most remote island is Tristan da Cunha, located in the South Atlantic Ocean.",
                "36. The country with the most pyramids is Sudan, not Egypt.",
                "37. There are more than 200 islands in Finland's archipelago.",
                "38. The oldest known city in the world is Damascus, Syria.",
                "39. Nepal is the only country without a rectangular flag.",
                "40. The Philippines is the only Asian country where Roman Catholicism is the predominant religion.",
                "41. The world's highest railway is in Peru, running through the Andes.",
                "42. The national symbol of Canada is the maple leaf.",
                "43. Thailand is the only Southeast Asian country never colonized by a European power.",
                "44. The world's largest sand island is Fraser Island in Australia.",
                "45. The longest fence in the world is the Dingo Fence in Australia, stretching over 5,600 kilometers.",
                "46. Greenland has the world's lowest population density.",
                "47. Madagascar is home to the world's smallest chameleon.",
                "48. The longest river in the world, by discharge, is the Amazon River.",
                "49. The world's most densely populated country is Monaco.",
                "50. The country with the most time zones is France, due to its overseas territories.",
                "51. Hawaii is the only U.S. state made up entirely of islands.",
                "52. The world's largest flower, the Rafflesia arnoldii, is found in Indonesia.",
                "53. The first country to grant women the right to vote was New Zealand in 1893.",
                "54. The national symbol of North Korea is the Kimjongilia flower.",
                "55. Finland has the highest coffee consumption per capita in the world.",
                "56. The world's largest tea producer is China.",
                "57. The national sport of Afghanistan is Buzkashi, where horse-mounted players attempt to place a goat carcass in a goal.",
                "58. The country with the most islands is Sweden.",
                "59. New Zealand is the only country with two official national anthems.",
                "60. The world's largest exporter of bananas is Ecuador.",
                "61. The currency of Cambodia is the Riel.",
                "62. The national bird of India is the Indian Peafowl, also known as the peacock.",
                "63. The world's highest battlefield is the Siachen Glacier in the Himalayas.",
                "64. The world's largest gold producer is China.",
                "65. The country with the most lakes is Canada.",
                "66. The national symbol of Mexico is the golden eagle.",
                "67. The world's largest salt flat is the Salar de Uyuni in Bolivia.",
                "68. The national flower of Japan is the cherry blossom.",
                "69. The world's largest producer of wine is Italy.",
                "70. The oldest known flag still in use is the flag of Denmark, adopted in 1219."
        ));
        MyFacts.addAll(Arrays.asList(
                "71. The country with the most time zones is France, due to its overseas territories.",
                "72. Hawaii is the only U.S. state made up entirely of islands.",
                "73. The world's largest flower, the Rafflesia arnoldii, is found in Indonesia.",
                "74. The first country to grant women the right to vote was New Zealand in 1893.",
                "75. The national symbol of North Korea is the Kimjongilia flower.",
                "76. Finland has the highest coffee consumption per capita in the world.",
                "77. The world's largest tea producer is China.",
                "78. The national sport of Afghanistan is Buzkashi, where horse-mounted players attempt to place a goat carcass in a goal.",
                "79. The country with the most islands is Sweden.",
                "80. New Zealand is the only country with two official national anthems.",
                "81. The world's largest exporter of bananas is Ecuador.",
                "82. The currency of Cambodia is the Riel.",
                "83. The national bird of India is the Indian Peafowl, also known as the peacock.",
                "84. The world's highest battlefield is the Siachen Glacier in the Himalayas.",
                "85. The world's largest gold producer is China.",
                "86. The country with the most lakes is Canada.",
                "87. The national symbol of Mexico is the golden eagle.",
                "88. The world's largest salt flat is the Salar de Uyuni in Bolivia.",
                "89. The national flower of Japan is the cherry blossom.",
                "90. The world's largest producer of wine is Italy.",
                "91. The oldest known flag still in use is the flag of Denmark, adopted in 1219.",
                "92. The country with the most UNESCO World Heritage Sites is Italy.",
                "93. The world's largest coral atoll is Kwajalein in the Marshall Islands.",
                "94. The country with the most internet users is China.",
                "95. The world's highest navigable lake is Lake Titicaca in Peru and Bolivia.",
                "96. The national animal of Scotland is the unicorn.",
                "97. Iceland is a country with no mosquitoes.",
                "98. Singapore is the only country in the world without farmland.",
                "99. The world's most remote island is Tristan da Cunha, located in the South Atlantic Ocean.",
                "100. The country with the most pyramids is Sudan, not Egypt.",
                "101. There are more than 200 islands in Finland's archipelago.",
                "102. The oldest known city in the world is Damascus, Syria.",
                "103. Nepal is the only country without a rectangular flag.",
                "104. The Philippines is the only Asian country where Roman Catholicism is the predominant religion.",
                "105. The world's highest railway is in Peru, running through the Andes.",
                "106. The national symbol of Canada is the maple leaf.",
                "107. Thailand is the only Southeast Asian country never colonized by a European power.",
                "108. The world's largest sand island is Fraser Island in Australia.",
                "109. The longest fence in the world is the Dingo Fence in Australia, stretching over 5,600 kilometers.",
                "110. Greenland has the world's lowest population density.",
                "111. Madagascar is home to the world's smallest chameleon.",
                "112. The longest river in the world, by discharge, is the Amazon River.",
                "113. The world's most densely populated country is Monaco.",
                "114. The country with the most time zones is France, due to its overseas territories.",
                "115. Hawaii is the only U.S. state made up entirely of islands.",
                "116. The world's largest flower, the Rafflesia arnoldii, is found in Indonesia.",
                "117. The first country to grant women the right to vote was New Zealand in 1893.",
                "118. The national symbol of North Korea is the Kimjongilia flower.",
                "119. Finland has the highest coffee consumption per capita in the world.",
                "120. The world's largest tea producer is China.",
                "121. The national sport of Afghanistan is Buzkashi, where horse-mounted players attempt to place a goat carcass in a goal.",
                "122. The country with the most islands is Sweden.",
                "123. New Zealand is the only country with two official national anthems.",
                "124. The world's largest exporter of bananas is Ecuador.",
                "125. The currency of Cambodia is the Riel.",
                "126. The national bird of India is the Indian Peafowl, also known as the peacock.",
                "127. The world's highest battlefield is the Siachen Glacier in the Himalayas.",
                "128. The world's largest gold producer is China.",
                "129. The country with the most lakes is Canada.",
                "130. The national symbol of Mexico is the golden eagle.",
                "131. The world's largest salt flat is the Salar de Uyuni in Bolivia.",
                "132. The national flower of Japan is the cherry blossom.",
                "133. The world's largest producer of wine is Italy.",
                "134. The oldest known flag still in use is the flag of Denmark, adopted in 1219.",
                "135. The country with the most UNESCO World Heritage Sites is Italy.",
                "136. The world's largest coral atoll is Kwajalein in the Marshall Islands.",
                "137. The country with the most internet users is China.",
                "138. The world's highest navigable lake is Lake Titicaca in Peru and Bolivia.",
                "139. The national animal of Scotland is the unicorn.",
                "140. Iceland is a country with no mosquitoes.",
                "141. Singapore is the only country in the world without farmland.",
                "142. The world's most remote island is Tristan da Cunha, located in the South Atlantic Ocean.",
                "143. The country with the most pyramids is Sudan, not Egypt.",
                "144. There are more than 200 islands in Finland's archipelago.",
                "145. The oldest known city in the world is Damascus, Syria.",
                "146. Nepal is the only country without a rectangular flag.",
                "147. The Philippines is the only Asian country where Roman Catholicism is the predominant religion.",
                "148. The world's highest railway is in Peru, running through the Andes.",
                "149. The national symbol of Canada is the maple leaf.",
                "150. Thailand is the only Southeast Asian country never colonized by a European power.",
                "151. The world's largest sand island is Fraser Island in Australia.",
                "152. The longest fence in the world is the Dingo Fence in Australia, stretching over 5,600 kilometers.",
                "153. Greenland has the world's lowest population density.",
                "154. Madagascar is home to the world's smallest chameleon.",
                "155. The longest river in the world, by discharge, is the Amazon River.",
                "156. The world's most densely populated country is Monaco.",
                "157. The country with the most time zones is France, due to its overseas territories.",
                "158. Hawaii is the only U.S. state made up entirely of islands.",
                "159. The world's largest flower, the Rafflesia arnoldii, is found in Indonesia.",
                "160. The first country to grant women the right to vote was New Zealand in 1893.",
                "161. The national symbol of North Korea is the Kimjongilia flower.",
                "162. Finland has the highest coffee consumption per capita in the world.",
                "163. The world's largest tea producer is China.",
                "164. The national sport of Afghanistan is Buzkashi, where horse-mounted players attempt to place a goat carcass in a goal.",
                "165. The country with the most islands is Sweden.",
                "166. New Zealand is the only country with two official national anthems.",
                "167. The world's largest exporter of bananas is Ecuador.",
                "168. The currency of Cambodia is the Riel.",
                "169. The national bird of India is the Indian Peafowl, also known as the peacock.",
                "170. The world's highest battlefield is the Siachen Glacier in the Himalayas.",
                "171. The world's largest gold producer is China.",
                "172. The country with the most lakes is Canada.",
                "173. The national symbol of Mexico is the golden eagle.",
                "174. The world's largest salt flat is the Salar de Uyuni in Bolivia.",
                "175. The national flower of Japan is the cherry blossom.",
                "176. The world's largest producer of wine is Italy.",
                "177. The oldest known flag still in use is the flag of Denmark, adopted in 1219.",
                "178. The country with the most UNESCO World Heritage Sites is Italy.",
                "179. The world's largest coral atoll is Kwajalein in the Marshall Islands.",
                "180. The country with the most internet users is China.",
                "181. The world's highest navigable lake is Lake Titicaca in Peru and Bolivia.",
                "182. The national animal of Scotland is the unicorn.",
                "183. Iceland is a country with no mosquitoes.",
                "184. Singapore is the only country in the world without farmland.",
                "185. The world's most remote island is Tristan da Cunha, located in the South Atlantic Ocean.",
                "186. The country with the most pyramids is Sudan, not Egypt.",
                "187. There are more than 200 islands in Finland's archipelago.",
                "188. The oldest known city in the world is Damascus, Syria.",
                "189. Nepal is the only country without a rectangular flag.",
                "190. The Philippines is the only Asian country where Roman Catholicism is the predominant religion.",
                "191. The world's highest railway is in Peru, running through the Andes.",
                "192. The national symbol of Canada is the maple leaf.",
                "193. Thailand is the only Southeast Asian country never colonized by a European power.",
                "194. The world's largest sand island is Fraser Island in Australia.",
                "195. The longest fence in the world is the Dingo Fence in Australia, stretching over 5,600 kilometers.",
                "196. Greenland has the world's lowest population density.",
                "197. Madagascar is home to the world's smallest chameleon.",
                "198. The longest river in the world, by discharge, is the Amazon River.",
                "199. The world's most densely populated country is Monaco.",
                "200. The country with the most time zones is France, due to its overseas territories.",
                "201. Hawaii is the only U.S. state made up entirely of islands.",
                "202. The world's largest flower, the Rafflesia arnoldii, is found in Indonesia.",
                "203. The first country to grant women the right to vote was New Zealand in 1893.",
                "204. The national symbol of North Korea is the Kimjongilia flower.",
                "205. Finland has the highest coffee consumption per capita in the world.",
                "206. The world's largest tea producer is China.",
                "207. The national sport of Afghanistan is Buzkashi, where horse-mounted players attempt to place a goat carcass in a goal.",
                "208. The country with the most islands is Sweden.",
                "209. New Zealand is the only country with two official national anthems.",
                "210. The world's largest exporter of bananas is Ecuador.",
                "211. The currency of Cambodia is the Riel.",
                "212. The national bird of India is the Indian Peafowl, also known as the peacock.",
                "213. The world's highest battlefield is the Siachen Glacier in the Himalayas.",
                "214. The world's largest gold producer is China.",
                "215. The country with the most lakes is Canada.",
                "216. The national symbol of Mexico is the golden eagle.",
                "217. The world's largest salt flat is the Salar de Uyuni in Bolivia.",
                "218. The national flower of Japan is the cherry blossom.",
                "219. The world's largest producer of wine is Italy.",
                "220. The oldest known flag still in use is the flag of Denmark, adopted in 1219.",
                "221. The country with the most UNESCO World Heritage Sites is Italy.",
                "222. The world's largest coral atoll is Kwajalein in the Marshall Islands.",
                "223. The country with the most internet users is China.",
                "224. The world's highest navigable lake is Lake Titicaca in Peru and Bolivia.",
                "225. The national animal of Scotland is the unicorn.",
                "226. Iceland is a country with no mosquitoes.",
                "227. Singapore is the only country in the world without farmland.",
                "228. The world's most remote island is Tristan da Cunha, located in the South Atlantic Ocean.",
                "229. The country with the most pyramids is Sudan, not Egypt.",
                "230. There are more than 200 islands in Finland's archipelago.",
                "231. The oldest known city in the world is Damascus, Syria.",
                "232. Nepal is the only country without a rectangular flag.",
                "233. The Philippines is the only Asian country where Roman Catholicism is the predominant religion.",
                "234. The world's highest railway is in Peru, running through the Andes.",
                "235. The national symbol of Canada is the maple leaf.",
                "236. Thailand is the only Southeast Asian country never colonized by a European power.",
                "237. The world's largest sand island is Fraser Island in Australia.",
                "238. The longest fence in the world is the Dingo Fence in Australia, stretching over 5,600 kilometers.",
                "239. Greenland has the world's lowest population density.",
                "240. Madagascar is home to the world's smallest chameleon.",
                "241. The longest river in the world, by discharge, is the Amazon River.",
                "242. The world's most densely populated country is Monaco.",
                "243. The country with the most time zones is France, due to its overseas territories.",
                "244. Hawaii is the only U.S. state made up entirely of islands."

                ));

        MyFacts.addAll(Arrays.asList(
                "245. The world's largest flower, the Rafflesia arnoldii, is found in Indonesia.",
                "246. The first country to grant women the right to vote was New Zealand in 1893.",
                "247. The national symbol of North Korea is the Kimjongilia flower.",
                "248. Finland has the highest coffee consumption per capita in the world.",
                "249. The world's largest tea producer is China.",
                "250. The national sport of Afghanistan is Buzkashi, where horse-mounted players attempt to place a goat carcass in a goal.",
                "251. The country with the most islands is Sweden.",
                "252. New Zealand is the only country with two official national anthems.",
                "253. The world's largest exporter of bananas is Ecuador.",
                "254. The currency of Cambodia is the Riel.",
                "255. The national bird of India is the Indian Peafowl, also known as the peacock.",
                "256. The world's highest battlefield is the Siachen Glacier in the Himalayas.",
                "257. The world's largest gold producer is China.",
                "258. The country with the most lakes is Canada.",
                "259. The national symbol of Mexico is the golden eagle.",
                "260. The world's largest salt flat is the Salar de Uyuni in Bolivia.",
                "261. The national flower of Japan is the cherry blossom.",
                "262. The world's largest producer of wine is Italy.",
                "263. The oldest known flag still in use is the flag of Denmark, adopted in 1219.",
                "264. The country with the most UNESCO World Heritage Sites is Italy.",
                "265. The world's largest coral atoll is Kwajalein in the Marshall Islands.",
                "266. The country with the most internet users is China.",
                "267. The world's highest navigable lake is Lake Titicaca in Peru and Bolivia.",
                "268. The national animal of Scotland is the unicorn.",
                "269. Iceland is a country with no mosquitoes.",
                "270. Singapore is the only country in the world without farmland.",
                "271. The world's most remote island is Tristan da Cunha, located in the South Atlantic Ocean.",
                "272. The country with the most pyramids is Sudan, not Egypt.",
                "273. There are more than 200 islands in Finland's archipelago.",
                "274. The oldest known city in the world is Damascus, Syria.",
                "275. Nepal is the only country without a rectangular flag.",
                "276. The Philippines is the only Asian country where Roman Catholicism is the predominant religion.",
                "277. The world's highest railway is in Peru, running through the Andes.",
                "278. The national symbol of Canada is the maple leaf.",
                "279. Thailand is the only Southeast Asian country never colonized by a European power.",
                "280. The world's largest sand island is Fraser Island in Australia.",
                "281. The longest fence in the world is the Dingo Fence in Australia, stretching over 5,600 kilometers.",
                "282. Greenland has the world's lowest population density.",
                "283. Madagascar is home to the world's smallest chameleon.",
                "284. The longest river in the world, by discharge, is the Amazon River.",
                "285. The world's most densely populated country is Monaco.",
                "286. The country with the most time zones is France, due to its overseas territories.",
                "287. Hawaii is the only U.S. state made up entirely of islands.",
                "288. The world's largest flower, the Rafflesia arnoldii, is found in Indonesia.",
                "289. The first country to grant women the right to vote was New Zealand in 1893.",
                "290. The national symbol of North Korea is the Kimjongilia flower.",
                "291. Finland has the highest coffee consumption per capita in the world.",
                "292. The world's largest tea producer is China.",
                "293. The national sport of Afghanistan is Buzkashi, where horse-mounted players attempt to place a goat carcass in a goal.",
                "294. The country with the most islands is Sweden.",
                "295. New Zealand is the only country with two official national anthems.",
                "296. The world's largest exporter of bananas is Ecuador.",
                "297. The currency of Cambodia is the Riel.",
                "298. The national bird of India is the Indian Peafowl, also known as the peacock.",
                "299. The world's highest battlefield is the Siachen Glacier in the Himalayas.",
                "300. The world's largest gold producer is China."
        ));


        MyFacts.addAll(Arrays.asList(
                "301. The country with the most lakes is Canada.",
                "302. The national symbol of Mexico is the golden eagle.",
                "303. The world's largest salt flat is the Salar de Uyuni in Bolivia.",
                "304. The national flower of Japan is the cherry blossom.",
                "305. The world's largest producer of wine is Italy.",
                "306. The oldest known flag still in use is the flag of Denmark, adopted in 1219.",
                "307. The country with the most UNESCO World Heritage Sites is Italy.",
                "308. The world's largest coral atoll is Kwajalein in the Marshall Islands.",
                "309. The country with the most internet users is China.",
                "310. The world's highest navigable lake is Lake Titicaca in Peru and Bolivia.",
                "311. The national animal of Scotland is the unicorn.",
                "312. Iceland is a country with no mosquitoes.",
                "313. Singapore is the only country in the world without farmland.",
                "314. The world's most remote island is Tristan da Cunha, located in the South Atlantic Ocean.",
                "315. The country with the most pyramids is Sudan, not Egypt.",
                "316. There are more than 200 islands in Finland's archipelago.",
                "317. The oldest known city in the world is Damascus, Syria.",
                "318. Nepal is the only country without a rectangular flag.",
                "319. The Philippines is the only Asian country where Roman Catholicism is the predominant religion.",
                "320. The world's highest railway is in Peru, running through the Andes.",
                "321. The national symbol of Canada is the maple leaf.",
                "322. Thailand is the only Southeast Asian country never colonized by a European power.",
                "323. The world's largest sand island is Fraser Island in Australia.",
                "324. The longest fence in the world is the Dingo Fence in Australia, stretching over 5,600 kilometers.",
                "325. Greenland has the world's lowest population density.",
                "326. Madagascar is home to the world's smallest chameleon.",
                "327. The longest river in the world, by discharge, is the Amazon River.",
                "328. The world's most densely populated country is Monaco.",
                "329. The country with the most time zones is France, due to its overseas territories.",
                "330. Hawaii is the only U.S. state made up entirely of islands.",
                "331. The world's largest flower, the Rafflesia arnoldii, is found in Indonesia.",
                "332. The first country to grant women the right to vote was New Zealand in 1893.",
                "333. The national symbol of North Korea is the Kimjongilia flower.",
                "334. Finland has the highest coffee consumption per capita in the world.",
                "335. The world's largest tea producer is China.",
                "336. The national sport of Afghanistan is Buzkashi, where horse-mounted players attempt to place a goat carcass in a goal.",
                "337. The country with the most islands is Sweden.",
                "338. New Zealand is the only country with two official national anthems.",
                "339. The world's largest exporter of bananas is Ecuador.",
                "340. The currency of Cambodia is the Riel.",
                "341. The national bird of India is the Indian Peafowl, also known as the peacock.",
                "342. The world's highest battlefield is the Siachen Glacier in the Himalayas.",
                "343. The world's largest gold producer is China.",
                "344. The country with the most lakes is Canada.",
                "345. The national symbol of Mexico is the golden eagle.",
                "346. The world's largest salt flat is the Salar de Uyuni in Bolivia.",
                "347. The national flower of Japan is the cherry blossom.",
                "348. The world's largest producer of wine is Italy.",
                "349. The oldest known flag still in use is the flag of Denmark, adopted in 1219.",
                "350. The country with the most UNESCO World Heritage Sites is Italy.",
                "351. The world's largest coral atoll is Kwajalein in the Marshall Islands.",
                "352. The country with the most internet users is China.",
                "353. The world's highest navigable lake is Lake Titicaca in Peru and Bolivia.",
                "354. The national animal of Scotland is the unicorn.",
                "355. Iceland is a country with no mosquitoes.",
                "356. Singapore is the only country in the world without farmland.",
                "357. The world's most remote island is Tristan da Cunha, located in the South Atlantic Ocean.",
                "358. The country with the most pyramids is Sudan, not Egypt.",
                "359. There are more than 200 islands in Finland's archipelago.",
                "360. The oldest known city in the world is Damascus, Syria.",
                "361. Nepal is the only country without a rectangular flag.",
                "362. The Philippines is the only Asian country where Roman Catholicism is the predominant religion.",
                "363. The world's highest railway is in Peru, running through the Andes.",
                "364. The national symbol of Canada is the maple leaf.",
                "365. Thailand is the only Southeast Asian country never colonized by a European power.",
                "366. The world's largest sand island is Fraser Island in Australia.",
                "367. The longest fence in the world is the Dingo Fence in Australia, stretching over 5,600 kilometers.",
                "368. Greenland has the world's lowest population density.",
                "369. Madagascar is home to the world's smallest chameleon.",
                "370. The longest river in the world, by discharge, is the Amazon River.",
                "371. The world's most densely populated country is Monaco.",
                "372. The country with the most time zones is France, due to its overseas territories.",
                "373. Hawaii is the only U.S. state made up entirely of islands.",
                "374. The world's largest flower, the Rafflesia arnoldii, is found in Indonesia.",
                "375. The first country to grant women the right to vote was New Zealand in 1893.",
                "376. The national symbol of North Korea is the Kimjongilia flower.",
                "377. Finland has the highest coffee consumption per capita in the world.",
                "378. The world's largest tea producer is China.",
                "379. The national sport of Afghanistan is Buzkashi, where horse-mounted players attempt to place a goat carcass in a goal.",
                "380. The country with the most islands is Sweden.",
                "381. New Zealand is the only country with two official national anthems.",
                "382. The world's largest exporter of bananas is Ecuador.",
                "383. The currency of Cambodia is the Riel.",
                "384. The national bird of India is the Indian Peafowl, also known as the peacock.",
                "385. The world's highest battlefield is the Siachen Glacier in the Himalayas.",
                "386. The world's largest gold producer is China.",
                "387. The country with the most lakes is Canada.",
                "388. The national symbol of Mexico is the golden eagle.",
                "389. The world's largest salt flat is the Salar de Uyuni in Bolivia.",
                "390. The national flower of Japan is the cherry blossom.",
                "391. The world's largest producer of wine is Italy.",
                "392. The oldest known flag still in use is the flag of Denmark, adopted in 1219.",
                "393. The country with the most UNESCO World Heritage Sites is Italy.",
                "394. The world's largest coral atoll is Kwajalein in the Marshall Islands.",
                "395. The country with the most internet users is China.",
                "396. The world's highest navigable lake is Lake Titicaca in Peru and Bolivia.",
                "397. The national animal of Scotland is the unicorn.",
                "398. Iceland is a country with no mosquitoes.",
                "399. Singapore is the only country in the world without farmland.",
                "400. The world's most remote island is Tristan da Cunha, located in the South Atlantic Ocean."
        ));

        MyFacts.addAll(Arrays.asList(
                "401. The country with the most pyramids is Sudan, not Egypt.",
                "402. There are more than 200 islands in Finland's archipelago.",
                "403. The oldest known city in the world is Damascus, Syria.",
                "404. Nepal is the only country without a rectangular flag.",
                "405. The Philippines is the only Asian country where Roman Catholicism is the predominant religion.",
                "406. The world's highest railway is in Peru, running through the Andes.",
                "407. The national symbol of Canada is the maple leaf.",
                "408. Thailand is the only Southeast Asian country never colonized by a European power.",
                "409. The world's largest sand island is Fraser Island in Australia.",
                "410. The longest fence in the world is the Dingo Fence in Australia, stretching over 5,600 kilometers.",
                "411. Greenland has the world's lowest population density.",
                "412. Madagascar is home to the world's smallest chameleon.",
                "413. The longest river in the world, by discharge, is the Amazon River.",
                "414. The world's most densely populated country is Monaco.",
                "415. The country with the most time zones is France, due to its overseas territories.",
                "416. Hawaii is the only U.S. state made up entirely of islands.",
                "417. The world's largest flower, the Rafflesia arnoldii, is found in Indonesia.",
                "418. The first country to grant women the right to vote was New Zealand in 1893.",
                "419. The national symbol of North Korea is the Kimjongilia flower.",
                "420. Finland has the highest coffee consumption per capita in the world.",
                "421. The world's largest tea producer is China.",
                "422. The national sport of Afghanistan is Buzkashi, where horse-mounted players attempt to place a goat carcass in a goal.",
                "423. The country with the most islands is Sweden.",
                "424. New Zealand is the only country with two official national anthems.",
                "425. The world's largest exporter of bananas is Ecuador.",
                "426. The currency of Cambodia is the Riel.",
                "427. The national bird of India is the Indian Peafowl, also known as the peacock.",
                "428. The world's highest battlefield is the Siachen Glacier in the Himalayas.",
                "429. The world's largest gold producer is China.",
                "430. The country with the most lakes is Canada.",
                "431. The national symbol of Mexico is the golden eagle.",
                "432. The world's largest salt flat is the Salar de Uyuni in Bolivia.",
                "433. The national flower of Japan is the cherry blossom.",
                "434. The world's largest producer of wine is Italy.",
                "435. The oldest known flag still in use is the flag of Denmark, adopted in 1219.",
                "436. The country with the most UNESCO World Heritage Sites is Italy.",
                "437. The world's largest coral atoll is Kwajalein in the Marshall Islands.",
                "438. The country with the most internet users is China.",
                "439. The world's highest navigable lake is Lake Titicaca in Peru and Bolivia.",
                "440. The national animal of Scotland is the unicorn.",
                "441. Iceland is a country with no mosquitoes.",
                "442. Singapore is the only country in the world without farmland.",
                "443. The world's most remote island is Tristan da Cunha, located in the South Atlantic Ocean.",
                "444. The country with the most pyramids is Sudan, not Egypt.",
                "445. There are more than 200 islands in Finland's archipelago.",
                "446. The oldest known city in the world is Damascus, Syria.",
                "447. Nepal is the only country without a rectangular flag.",
                "448. The Philippines is the only Asian country where Roman Catholicism is the predominant religion.",
                "449. The world's highest railway is in Peru, running through the Andes.",
                "450. The national symbol of Canada is the maple leaf.",
                "451. Thailand is the only Southeast Asian country never colonized by a European power.",
                "452. The world's largest sand island is Fraser Island in Australia.",
                "453. The longest fence in the world is the Dingo Fence in Australia, stretching over 5,600 kilometers.",
                "454. Greenland has the world's lowest population density.",
                "455. Madagascar is home to the world's smallest chameleon.",
                "456. The longest river in the world, by discharge, is the Amazon River.",
                "457. The world's most densely populated country is Monaco.",
                "458. The country with the most time zones is France, due to its overseas territories.",
                "459. Hawaii is the only U.S. state made up entirely of islands.",
                "460. The world's largest flower, the Rafflesia arnoldii, is found in Indonesia.",
                "461. The first country to grant women the right to vote was New Zealand in 1893.",
                "462. The national symbol of North Korea is the Kimjongilia flower.",
                "463. Finland has the highest coffee consumption per capita in the world.",
                "464. The world's largest tea producer is China.",
                "465. The national sport of Afghanistan is Buzkashi, where horse-mounted players attempt to place a goat carcass in a goal.",
                "466. The country with the most islands is Sweden.",
                "467. New Zealand is the only country with two official national anthems.",
                "468. The world's largest exporter of bananas is Ecuador.",
                "469. The currency of Cambodia is the Riel.",
                "470. The national bird of India is the Indian Peafowl, also known as the peacock.",
                "471. The world's highest battlefield is the Siachen Glacier in the Himalayas.",
                "472. The world's largest gold producer is China.",
                "473. The country with the most lakes is Canada.",
                "474. The national symbol of Mexico is the golden eagle.",
                "475. The world's largest salt flat is the Salar de Uyuni in Bolivia.",
                "476. The national flower of Japan is the cherry blossom.",
                "477. The world's largest producer of wine is Italy.",
                "478. The oldest known flag still in use is the flag of Denmark, adopted in 1219.",
                "479. The country with the most UNESCO World Heritage Sites is Italy.",
                "480. The world's largest coral atoll is Kwajalein in the Marshall Islands.",
                "481. The country with the most internet users is China.",
                "482. The world's highest navigable lake is Lake Titicaca in Peru and Bolivia.",
                "483. The national animal of Scotland is the unicorn.",
                "484. Iceland is a country with no mosquitoes.",
                "485. Singapore is the only country in the world without farmland.",
                "486. The world's most remote island is Tristan da Cunha, located in the South Atlantic Ocean.",
                "487. The country with the most pyramids is Sudan, not Egypt.",
                "488. There are more than 200 islands in Finland's archipelago.",
                "489. The oldest known city in the world is Damascus, Syria.",
                "490. Nepal is the only country without a rectangular flag.",
                "491. The Philippines is the only Asian country where Roman Catholicism is the predominant religion.",
                "492. The world's highest railway is in Peru, running through the Andes.",
                "493. The national symbol of Canada is the maple leaf.",
                "494. Thailand is the only Southeast Asian country never colonized by a European power.",
                "495. The world's largest sand island is Fraser Island in Australia.",
                "496. The longest fence in the world is the Dingo Fence in Australia, stretching over 5,600 kilometers.",
                "497. Greenland has the world's lowest population density.",
                "498. Madagascar is home to the world's smallest chameleon.",
                "499. The longest river in the world, by discharge, is the Amazon River.",
                "500. The world's most densely populated country is Monaco."
        ));
        MyFacts.addAll(Arrays.asList(
                "501. The country with the most time zones is France, due to its overseas territories.",
                "502. Hawaii is the only U.S. state made up entirely of islands.",
                "503. The world's largest flower, the Rafflesia arnoldii, is found in Indonesia.",
                "504. The first country to grant women the right to vote was New Zealand in 1893.",
                "505. The national symbol of North Korea is the Kimjongilia flower.",
                "506. Finland has the highest coffee consumption per capita in the world.",
                "507. The world's largest tea producer is China.",
                "508. The national sport of Afghanistan is Buzkashi, where horse-mounted players attempt to place a goat carcass in a goal.",
                "509. The country with the most islands is Sweden.",
                "510. New Zealand is the only country with two official national anthems.",
                "511. The world's largest exporter of bananas is Ecuador.",
                "512. The currency of Cambodia is the Riel.",
                "513. The national bird of India is the Indian Peafowl, also known as the peacock.",
                "514. The world's highest battlefield is the Siachen Glacier in the Himalayas.",
                "515. The world's largest gold producer is China.",
                "516. The country with the most lakes is Canada.",
                "517. The national symbol of Mexico is the golden eagle.",
                "518. The world's largest salt flat is the Salar de Uyuni in Bolivia.",
                "519. The national flower of Japan is the cherry blossom.",
                "520. The world's largest producer of wine is Italy.",
                "521. The oldest known flag still in use is the flag of Denmark, adopted in 1219.",
                "522. The country with the most UNESCO World Heritage Sites is Italy.",
                "523. The world's largest coral atoll is Kwajalein in the Marshall Islands.",
                "524. The country with the most internet users is China.",
                "525. The world's highest navigable lake is Lake Titicaca in Peru and Bolivia.",
                "526. The national animal of Scotland is the unicorn.",
                "527. Iceland is a country with no mosquitoes.",
                "528. Singapore is the only country in the world without farmland.",
                "529. The world's most remote island is Tristan da Cunha, located in the South Atlantic Ocean.",
                "530. The country with the most pyramids is Sudan, not Egypt.",
                "531. There are more than 200 islands in Finland's archipelago.",
                "532. The oldest known city in the world is Damascus, Syria.",
                "533. Nepal is the only country without a rectangular flag.",
                "534. The Philippines is the only Asian country where Roman Catholicism is the predominant religion.",
                "535. The world's highest railway is in Peru, running through the Andes.",
                "536. The national symbol of Canada is the maple leaf.",
                "537. Thailand is the only Southeast Asian country never colonized by a European power.",
                "538. The world's largest sand island is Fraser Island in Australia.",
                "539. The longest fence in the world is the Dingo Fence in Australia, stretching over 5,600 kilometers.",
                "540. Greenland has the world's lowest population density.",
                "541. Madagascar is home to the world's smallest chameleon.",
                "542. The longest river in the world, by discharge, is the Amazon River.",
                "543. The world's most densely populated country is Monaco.",
                "544. The country with the most time zones is France, due to its overseas territories.",
                "545. Hawaii is the only U.S. state made up entirely of islands.",
                "546. The world's largest flower, the Rafflesia arnoldii, is found in Indonesia.",
                "547. The first country to grant women the right to vote was New Zealand in 1893.",
                "548. The national symbol of North Korea is the Kimjongilia flower.",
                "549. Finland has the highest coffee consumption per capita in the world.",
                "550. The world's largest tea producer is China.",
                "551. The national sport of Afghanistan is Buzkashi, where horse-mounted players attempt to place a goat carcass in a goal.",
                "552. The country with the most islands is Sweden.",
                "553. New Zealand is the only country with two official national anthems.",
                "554. The world's largest exporter of bananas is Ecuador.",
                "555. The currency of Cambodia is the Riel.",
                "556. The national bird of India is the Indian Peafowl, also known as the peacock.",
                "557. The world's highest battlefield is the Siachen Glacier in the Himalayas.",
                "558. The world's largest gold producer is China.",
                "559. The country with the most lakes is Canada.",
                "560. The national symbol of Mexico is the golden eagle.",
                "561. The world's largest salt flat is the Salar de Uyuni in Bolivia.",
                "562. The national flower of Japan is the cherry blossom.",
                "563. The world's largest producer of wine is Italy.",
                "564. The oldest known flag still in use is the flag of Denmark, adopted in 1219.",
                "565. The country with the most UNESCO World Heritage Sites is Italy.",
                "566. The world's largest coral atoll is Kwajalein in the Marshall Islands.",
                "567. The country with the most internet users is China.",
                "568. The world's highest navigable lake is Lake Titicaca in Peru and Bolivia.",
                "569. The national animal of Scotland is the unicorn.",
                "570. Iceland is a country with no mosquitoes.",
                "571. Singapore is the only country in the world without farmland.",
                "572. The world's most remote island is Tristan da Cunha, located in the South Atlantic Ocean.",
                "573. The country with the most pyramids is Sudan, not Egypt.",
                "574. There are more than 200 islands in Finland's archipelago.",
                "575. The oldest known city in the world is Damascus, Syria.",
                "576. Nepal is the only country without a rectangular flag.",
                "577. The Philippines is the only Asian country where Roman Catholicism is the predominant religion.",
                "578. The world's highest railway is in Peru, running through the Andes.",
                "579. The national symbol of Canada is the maple leaf.",
                "580. Thailand is the only Southeast Asian country never colonized by a European power.",
                "581. The world's largest sand island is Fraser Island in Australia.",
                "582. The longest fence in the world is the Dingo Fence in Australia, stretching over 5,600 kilometers.",
                "583. Greenland has the world's lowest population density.",
                "584. Madagascar is home to the world's smallest chameleon.",
                "585. The longest river in the world, by discharge, is the Amazon River.",
                "586. The world's most densely populated country is Monaco.",
                "587. The country with the most time zones is France, due to its overseas territories.",
                "588. Hawaii is the only U.S. state made up entirely of islands.",
                "589. The world's largest flower, the Rafflesia arnoldii, is found in Indonesia.",
                "590. The first country to grant women the right to vote was New Zealand in 1893.",
                "591. The national symbol of North Korea is the Kimjongilia flower.",
                "592. Finland has the highest coffee consumption per capita in the world.",
                "593. The world's largest tea producer is China.",
                "594. The national sport of Afghanistan is Buzkashi, where horse-mounted players attempt to place a goat carcass in a goal.",
                "595. The country with the most islands is Sweden.",
                "596. New Zealand is the only country with two official national anthems.",
                "597. The world's largest exporter of bananas is Ecuador.",
                "598. The currency of Cambodia is the Riel.",
                "599. The national bird of India is the Indian Peafowl, also known as the peacock.",
                "600. The world's highest battlefield is the Siachen Glacier in the Himalayas."
        ));

        MyFacts.addAll(Arrays.asList(
                "601. The world's largest sand island is Fraser Island in Australia.",
                "602. The longest fence in the world is the Dingo Fence in Australia, stretching over 5,600 kilometers.",
                "603. Greenland has the world's lowest population density.",
                "604. Madagascar is home to the world's smallest chameleon.",
                "605. The longest river in the world, by discharge, is the Amazon River.",
                "606. The world's most densely populated country is Monaco.",
                "607. The country with the most time zones is France, due to its overseas territories.",
                "608. Hawaii is the only U.S. state made up entirely of islands.",
                "609. The world's largest flower, the Rafflesia arnoldii, is found in Indonesia.",
                "610. The first country to grant women the right to vote was New Zealand in 1893.",
                "611. The national symbol of North Korea is the Kimjongilia flower.",
                "612. Finland has the highest coffee consumption per capita in the world.",
                "613. The world's largest tea producer is China.",
                "614. The national sport of Afghanistan is Buzkashi, where horse-mounted players attempt to place a goat carcass in a goal.",
                "615. The country with the most islands is Sweden.",
                "616. New Zealand is the only country with two official national anthems.",
                "617. The world's largest exporter of bananas is Ecuador.",
                "618. The currency of Cambodia is the Riel.",
                "619. The national bird of India is the Indian Peafowl, also known as the peacock.",
                "620. The world's highest battlefield is the Siachen Glacier in the Himalayas.",
                "621. The world's largest gold producer is China.",
                "622. The country with the most lakes is Canada.",
                "623. The national symbol of Mexico is the golden eagle.",
                "624. The world's largest salt flat is the Salar de Uyuni in Bolivia.",
                "625. The national flower of Japan is the cherry blossom.",
                "626. The world's largest producer of wine is Italy.",
                "627. The oldest known flag still in use is the flag of Denmark, adopted in 1219.",
                "628. The country with the most UNESCO World Heritage Sites is Italy.",
                "629. The world's largest coral atoll is Kwajalein in the Marshall Islands.",
                "630. The country with the most internet users is China.",
                "631. The world's highest navigable lake is Lake Titicaca in Peru and Bolivia.",
                "632. The national animal of Scotland is the unicorn.",
                "633. Iceland is a country with no mosquitoes.",
                "634. Singapore is the only country in the world without farmland.",
                "635. The world's most remote island is Tristan da Cunha, located in the South Atlantic Ocean.",
                "636. The country with the most pyramids is Sudan, not Egypt.",
                "637. There are more than 200 islands in Finland's archipelago.",
                "638. The oldest known city in the world is Damascus, Syria.",
                "639. Nepal is the only country without a rectangular flag.",
                "640. The Philippines is the only Asian country where Roman Catholicism is the predominant religion.",
                "641. The world's highest railway is in Peru, running through the Andes.",
                "642. The national symbol of Canada is the maple leaf.",
                "643. Thailand is the only Southeast Asian country never colonized by a European power.",
                "644. The world's largest sand island is Fraser Island in Australia.",
                "645. The longest fence in the world is the Dingo Fence in Australia, stretching over 5,600 kilometers.",
                "646. Greenland has the world's lowest population density.",
                "647. Madagascar is home to the world's smallest chameleon.",
                "648. The longest river in the world, by discharge, is the Amazon River.",
                "649. The world's most densely populated country is Monaco.",
                "650. The country with the most time zones is France, due to its overseas territories.",
                "651. Hawaii is the only U.S. state made up entirely of islands.",
                "652. The world's largest flower, the Rafflesia arnoldii, is found in Indonesia.",
                "653. The first country to grant women the right to vote was New Zealand in 1893.",
                "654. The national symbol of North Korea is the Kimjongilia flower.",
                "655. Finland has the highest coffee consumption per capita in the world.",
                "656. The world's largest tea producer is China.",
                "657. The national sport of Afghanistan is Buzkashi, where horse-mounted players attempt to place a goat carcass in a goal.",
                "658. The country with the most islands is Sweden.",
                "659. New Zealand is the only country with two official national anthems.",
                "660. The world's largest exporter of bananas is Ecuador.",
                "661. The currency of Cambodia is the Riel.",
                "662. The national bird of India is the Indian Peafowl, also known as the peacock.",
                "663. The world's highest battlefield is the Siachen Glacier in the Himalayas.",
                "664. The world's largest gold producer is China.",
                "665. The country with the most lakes is Canada.",
                "666. The national symbol of Mexico is the golden eagle.",
                "667. The world's largest salt flat is the Salar de Uyuni in Bolivia.",
                "668. The national flower of Japan is the cherry blossom.",
                "669. The world's largest producer of wine is Italy.",
                "670. The oldest known flag still in use is the flag of Denmark, adopted in 1219.",
                "671. The country with the most UNESCO World Heritage Sites is Italy.",
                "672. The world's largest coral atoll is Kwajalein in the Marshall Islands.",
                "673. The country with the most internet users is China.",
                "674. The world's highest navigable lake is Lake Titicaca in Peru and Bolivia.",
                "675. The national animal of Scotland is the unicorn.",
                "676. Iceland is a country with no mosquitoes.",
                "677. Singapore is the only country in the world without farmland.",
                "678. The world's most remote island is Tristan da Cunha, located in the South Atlantic Ocean.",
                "679. The country with the most pyramids is Sudan, not Egypt.",
                "680. There are more than 200 islands in Finland's archipelago.",
                "681. The oldest known city in the world is Damascus, Syria.",
                "682. Nepal is the only country without a rectangular flag.",
                "683. The Philippines is the only Asian country where Roman Catholicism is the predominant religion.",
                "684. The world's highest railway is in Peru, running through the Andes.",
                "685. The national symbol of Canada is the maple leaf.",
                "686. Thailand is the only Southeast Asian country never colonized by a European power.",
                "687. The world's largest sand island is Fraser Island in Australia.",
                "688. The longest fence in the world is the Dingo Fence in Australia, stretching over 5,600 kilometers.",
                "689. Greenland has the world's lowest population density.",
                "690. Madagascar is home to the world's smallest chameleon.",
                "691. The longest river in the world, by discharge, is the Amazon River.",
                "692. The world's most densely populated country is Monaco.",
                "693. The country with the most time zones is France, due to its overseas territories.",
                "694. Hawaii is the only U.S. state made up entirely of islands.",
                "695. The world's largest flower, the Rafflesia arnoldii, is found in Indonesia.",
                "696. The first country to grant women the right to vote was New Zealand in 1893.",
                "697. The national symbol of North Korea is the Kimjongilia flower.",
                "698. Finland has the highest coffee consumption per capita in the world.",
                "699. The world's largest tea producer is China.",
                "700. The national sport of Afghanistan is Buzkashi, where horse-mounted players attempt to place a goat carcass in a goal."
        ));

        MyFacts.addAll(Arrays.asList(
                "701. The country with the highest number of lakes is Finland.",
                "702. The world's largest exporter of coffee is Brazil.",
                "703. The national animal of Australia is the kangaroo.",
                "704. The Great Wall of China is visible from space.",
                "705. The smallest independent country in Africa is Seychelles.",
                "706. The world's longest railway platform is in Gorakhpur, India.",
                "707. The currency of South Korea is the Korean Won.",
                "708. Mount Everest, the world's highest peak, is located in Nepal.",
                "709. The national dish of Italy is pasta.",
                "710. The country with the most volcanoes is Indonesia.",
                "711. The world's largest art gallery is the State Hermitage Museum in Russia.",
                "712. The currency of Switzerland is the Swiss Franc.",
                "713. The driest inhabited place on Earth is Aswan, Egypt.",
                "714. The national bird of the United States is the Bald Eagle.",
                "715. The world's largest monolith is Mount Augustus in Australia.",
                "716. The currency of Japan is the Japanese Yen.",
                "717. The highest mountain in North America is Denali in Alaska.",
                "718. The world's oldest national flag still in use is that of Denmark.",
                "719. The national dish of Japan is sushi.",
                "720. The country with the most official languages is South Africa.",
                "721. The world's largest ocean is the Pacific Ocean.",
                "722. The currency of India is the Indian Rupee.",
                "723. The national flower of China is the peony.",
                "724. The world's largest saltwater lake by surface area is the Caspian Sea.",
                "725. The national animal of Canada is the beaver.",
                "726. The currency of Mexico is the Mexican Peso.",
                "727. The country with the most UNESCO World Heritage Sites is China.",
                "728. The world's largest canyon is the Grand Canyon in the United States.",
                "729. The national dish of France is coq au vin.",
                "730. The currency of Brazil is the Brazilian Real.",
                "731. The world's highest waterfall is Angel Falls in Venezuela.",
                "732. The national flower of France is the Lily.",
                "733. The world's largest hot desert is the Sahara Desert.",
                "734. The currency of Russia is the Russian Ruble.",
                "735. The national dish of Thailand is pad Thai.",
                "736. The world's largest island country is Indonesia.",
                "737. The currency of Canada is the Canadian Dollar.",
                "738. The national bird of China is the red-crowned crane.",
                "739. The world's largest bay is Hudson Bay in Canada.",
                "740. The currency of Australia is the Australian Dollar.",
                "741. The national dish of China is Peking duck.",
                "742. The world's largest natural arch is the Rainbow Bridge in Utah, USA.",
                "743. The currency of South Africa is the South African Rand.",
                "744. The national bird of Brazil is the rufous-bellied thrush.",
                "745. The world's largest mangrove forest is the Sundarbans in Bangladesh.",
                "746. The currency of Argentina is the Argentine Peso.",
                "747. The national dish of India is curry.",
                "748. The world's largest cave chamber is Sarawak Chamber in Malaysia.",
                "749. The currency of Germany is the Euro.",
                "750. The national animal of South Africa is the springbok."
        ));

        MyFacts.addAll(Arrays.asList(
                "751. The currency of Egypt is the Egyptian Pound.",
                "752. The national bird of Australia is the emu.",
                "753. The world's largest iceberg is the B-15 iceberg, which measured about 11,000 square kilometers.",
                "754. The currency of South Korea is the Korean Won.",
                "755. The national dish of Mexico is mole poblano.",
                "756. The world's largest lagoon is the Great Barrier Reef Lagoon in Australia.",
                "757. The currency of Saudi Arabia is the Saudi Riyal.",
                "758. The national flower of India is the lotus.",
                "759. The world's largest delta is the Sundarbans Delta in Bangladesh and India.",
                "760. The currency of Nigeria is the Nigerian Naira.",
                "761. The national bird of Argentina is the Rufous Hornero.",
                "762. The world's largest desert by area is Antarctica.",
                "763. The currency of France is the Euro.",
                "764. The national dish of Italy is pasta.",
                "765. The world's largest man-made island is Palm Jumeirah in Dubai, UAE.",
                "766. The currency of Spain is the Euro.",
                "767. The national bird of Russia is the double-headed eagle.",
                "768. The world's largest natural lake is the Caspian Sea.",
                "769. The currency of Peru is the Peruvian Sol.",
                "770. The national dish of Japan is sushi.",
                "771. The world's largest marshland is the Pantanal in Brazil, Paraguay, and Bolivia.",
                "772. The currency of South Africa is the South African Rand.",
                "773. The national flower of Brazil is the Cattleya Orchid.",
                "774. The world's largest statue is the Statue of Unity in India.",
                "775. The currency of China is the Chinese Yuan.",
                "776. The national bird of Canada is the common loon.",
                "777. The world's largest rock is Mount Augustus in Australia.",
                "778. The currency of Japan is the Japanese Yen.",
                "779. The national dish of Thailand is pad Thai.",
                "780. The world's largest mud volcano is the Baratang Mud Volcano in India.",
                "781. The currency of Mexico is the Mexican Peso.",
                "782. The national flower of China is the plum blossom.",
                "783. The world's largest glacier is the Lambert Glacier in Antarctica.",
                "784. The currency of Canada is the Canadian Dollar.",
                "785. The national dish of China is Peking duck.",
                "786. The world's largest coral reef system is the Great Barrier Reef in Australia.",
                "787. The currency of Brazil is the Brazilian Real.",
                "788. The national bird of China is the red-crowned crane.",
                "789. The world's largest salt flat is the Salar de Uyuni in Bolivia.",
                "790. The currency of Australia is the Australian Dollar.",
                "791. The national dish of India is curry.",
                "792. The world's largest saltwater lake by surface area is the Caspian Sea.",
                "793. The currency of South Africa is the South African Rand.",
                "794. The national bird of Brazil is the rufous-bellied thrush.",
                "795. The world's largest mangrove forest is the Sundarbans in Bangladesh.",
                "796. The currency of Argentina is the Argentine Peso.",
                "797. The national dish of Italy is pasta.",
                "798. The world's largest cave chamber is Sarawak Chamber in Malaysia.",
                "799. The currency of Germany is the Euro.",
                "800. The national animal of South Africa is the springbok."
        ));



        Btn_Next_Fact.setOnClickListener(view -> {

            currentIndex++;
            if (currentIndex >= MyFacts.size()) {
                currentIndex = 0; // start over if we've reached the end
            }
            Txt_Fact.setText(MyFacts.get(currentIndex));


        });

    }

    private void configureNextButtonHelperSound()
    {
        final MediaPlayer mp = MediaPlayer.create(this, R.raw.modernclick);

        if (!MainMenu.flag){
            mp.setVolume(0,0);
        }
        else{
            mp.setVolume(0,1);
        }

        mp.start();
    }

    private void ButtonsNav() {
        navToMain.setOnClickListener(view -> {
            configureNextButtonHelperSound();
            startActivity(new Intent(Fun_Facts.this, MainMenu.class));
            overridePendingTransition(R.anim.slide_in,R.anim.slide_out);


        });


    }

    private void  Mute_UnMute() {



        mute_unmute.setOnClickListener(view -> {
            i[0]++;
            new Handler();

            if (i[0] % 2==0) {

                Toast.makeText(Fun_Facts.this, "UnMute", Toast.LENGTH_SHORT).show();
                flag = true;
                mute_unmute.setImageResource(R.mipmap.mutenewproblem11);

            } else {
                Toast.makeText(Fun_Facts.this, "Mute", Toast.LENGTH_SHORT).show();
                flag = false;
                mute_unmute.setImageResource(R.mipmap.mutenewproblem22);
            }
        });

    }


}